---
- hosts: 192.168.6.122,192.168.6.123
  remote_user: root
  tasks:
  - name: copy jdk remote hosts
    copy: src=/package/java_jdk.tar.gz dest=/bubidata/server/
  - name: tar xvf java_jdk.tar.gz
    shell: chdir=/bubidata/server tar zxf java_jdk.tar.gz
  - name: check jdk variable 
    shell: cat /etc/profile
    register: result
  - name: java_profile config
    shell: /bin/echo {{ item }} >> /etc/profile && source /etc/profile
    when: result.stdout.find('JAVA_HOME') == -1
    with_items:
      - export JAVA_HOME=/bubidata/server/java
      - export CLASS_PATH=.:\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar
      - export PATH=\$JAVA_HOME/bin:\$PATH
  - name: source profile
    shell: source /etc/profile