---
- hosts: 192.168.5.100
  remote_user: root
  vars:
  src_host_path: /home/jekins/.jenkins/workspace/test-yinuojr-discovery/target
  localhost_host_path: /data/backup/yinuojr-discovery/target
  project_name: yinuojr-discovery
  src_host_ip: 192.168.2.40

  tasks:
    - name: create directory
      file: path={{ item }} state=directory
      with_items:
        - "{{ src_host_path }}"
        - "{{ localhost_host_path }}"
        - "{{ src_host_ip }}"
        - "{{ project_name }}"

    - name: scp src yinuojr-discovery package to localhost
      command: "sshpass -pbubi scp -o StrictHostKeyChecking=no root@{{ src_host_ip }}:{{ src_host_path }}/{{ project_name }}.zip {{ localhost_host_path }}"

    - name: check yinuojr-discovery package
      shell: cd {{ localhost_host_path }} ; ls -lrt {{ yinuojr-discovery }}.zip