---
- hosts: 192.168.6.123
  remote_user: root
  vars:
    local_host_file: /root/.jenkins/workspace/pre-yinuojr-evidence/target
    remote_host_file: /root/.jenkins/workspace/pre-yinuojr-evidence/target
    data_path: /bubidata/server/data
    project_backup_path: /data/backup
    project_name: yinuojr-evidence
    run_port: 32000
    source_package_host_ip: 192.168.2.100
    
  tasks:
    - name: 创建变量对应的目录
      file: path={{ item }} state=directory
      with_items:
        - "{{ local_host_file }}/"
        - "{{ remote_host_file }}/"
        - "{{ project_backup_path }}/"
        - "{{ project_name }}/"
        - "{{ data_path }}/"

    - name: from remote host scp java package to local host
      command: "sshpass -pbubi scp -o StrictHostKeyChecking=no root@192.168.2.110:{{ remote_host_file }}/{{ project_name }}.zip {{ local_host_file }}"  
  
    - name: check local package md5sum
      command: "sshpass -pbubi ssh root@192.168.2.110 'ls -lrt {{ remote_host_file }}/{{ project_name }}.zip;md5sum {{ remote_host_file }}/{{ project_name }}.zip'"
      register: check_scp
    - debug: msg={{check_scp.stdout_lines}}
  
    - name: md5sum local
      command: "sshpass -p bubi ssh root@192.168.6.123 'ls -lrt {{ local_host_file }}/{{ project_name }}.zip;md5sum {{ local_host_file }}/{{ project_name }}.zip'"
      register: check_local
    - debug: msg={{check_local.stdout_lines}}

    - name: stop java service
      shell: chdir={{ data_path }}/{{ project_name }}/bin/ sh launch stop 

    - name: check service stop 
      wait_for: port={{ run_port }} delay=3 state=stopped timeout=10

    - name: backup current java package 
      shell: tar czvf {{ project_backup_path }}/{{ project_name}}.tar.gz {{ data_path }}/{{ project_name}}

    - name: delete current package
      shell: rm -rf {{ data_path }}/{{ project_name }} && rm -rf {{ data_path }}/{{ project_name }}.zip

    #- name: copy java package to dest host 
      #copy: src={{ local_host_file }}/{{ project_name }}.zip dest={{ data_path }}/
      #file: src={{ local_host_file }}/{{ project_name }}.zip dest={{ data_path }}/

    - name: unzip java package
      shell: chdir={{ data_path }}/{{ project_name }}/  unzip {{ data_path }}/{{ project_name }}.zip