---
- hosts: 192.168.6.123
  remote_user: root
  vars:
    local_host_file: /root/.jenkins/workspace/pre-yinuojr-evidence/target
    remote_host_file: /package/pre-yinuojr-evidence/target
    data_path: /bubidata/server/data
    project_backup_path: /data/backup
    project_name: yinuojr-evidence
    run_port: 32000

  tasks:
    - name: 创建变量对应的目录
      file: path={{ item }} state=directory
      with_items:
        - "{{ local_host_file }}/"
        - "{{ remote_host_file }}/"
        - "{{ project_backup_path }}/"
        - "{{ project_name }}/"
        - "{{ data_path }}/"

    - name: debug md5sum
      command: "sshpass -pbubi ssh -o StrictHostKeyChecking=no root@192.168.2.110 'ls -l /root/.jenkins/workspace/pre-yinuojr-evidence/target/yinuojr-evidence.zip;md5sum  /root/.jenkins/workspace/pre-yinuojr-evidence/target/yinuojr-evidence.zip'"    
		  register: check_out
    - debug: msg={{ check_out.stdout_lines }}

    - name: 停止运行的java服务
      shell: chdir={{ data_path }}/{{ project_name }}/bin/ sh launch stop 

    - name: 验证服务是否关闭
      wait_for: port={{ run_port }} delay=3 state=stopped timeout=10

    - name: 备份现有旧的服务包
      shell: tar czvf {{ project_backup_path }}/{{ project_name}}.tar.gz {{ data_path }}/{{ project_name}}

    - name: 删除服务包
      shell: rm -rf {{ data_path }}/{{ project_name }} && rm -rf {{ data_path }}/{{ project_name }}.zip

    - name: 拷贝新版java服务包并解压
      #copy: src={{ local_host_file }}/{{ project_name }}.zip dest={{ data_path }}/
      file: src={{ local_host_file }}/{{ project_name }}.zip dest={{ data_path }}/

    - name: 解压文件
      shell: chdir={{ data_path }}/{{ project_name }}/  unzip {{ data_path }}/{{ project_name }}.zip