---
- hosts: 192.168.6.123
  remote_user: root
  vars:
    local_host_file: /root/.jenkins/workspace/pre-yinuojr-evidence/target
    remote_host_file: /root/.jenkins/workspace/pre-yinuojr-evidence/target
    data_path: /bubidata/server/data
    project_backup_path: /data/backup
    project_name: yinuojr-evidence
    run_port: 32000

  tasks:
    - name: Create directory
      file: path={{ item }} state=directory
      with_items:
        - "{{ local_host_file }}/"
        - "{{ remote_host_file }}/"
        - "{{ project_backup_path }}/"
        - "{{ project_name }}/"
        - "{{ data_path }}/"

    - name: stop tomcat
      shell: chdir={{ data_path }}/{{ project_name }}/bin/ sh launch stop 
    - name: 验证服务是否关闭
      wait_for: port={{ run_port }} delay=3 state=stopped timeout=10

    - name: backup local java package
      shell: tar czvf {{ project_backup_path }}/{{ project_name}}.tar.gz {{ data_path }}/{{ project_name}}
