---
- name: 建立备份目录
  file: dest={{ backup_dir }} state=directory
- name: stop tomcat.
  shell: su -c  {{ tomcat_root }}/bin/shutdown.sh qsc_user
- name: 稍等一下
  pause: seconds=10
- name: 验证服务是否关闭
  wait_for: port={{ RUN_PORT }} delay=3 state=stopped timeout=10
- name: 备份现有程序
  command: mv "{{ tomcat_root }}"/webapps "{{ backup_dir }}/{{ module }}"-webapps.bak
- name: 建立webapps目录
  file: dest={{ tomcat_root }}/webapps state=directory owner=qsc_user group=qsc_user
- name: unzip project package
  shell: unzip xxxx.zip 
- name: start tomcat.
  shell: su -c  {{ tomcat_root }}/bin/startup.sh qsc_user
- name: 等待服务启动
  wait_for: port={{ RUN_PORT }} delay=5 timeout=30
- name: 验证服务是否重启成功
  shell:  curl http://localhost:port
- name: 重启服务执行完毕
  shell: echo "Restart Successful !!!"